### ISSUE TITLE
truffle deploy failed

### ISSUE THREAD

**Issue by wuyuyue** [cryptape/cita-truffle-box#26]
```
truffle deploy
Error: Returned error: Method not found
    at Object.ErrorResponse (C:\Users\wu\AppData\Roaming\nvm\v11.10.0\node_modules\truffle\build\webpack:\~\web3-eth\~\web3-core-helpers\src\errors.js:29:1)
    at C:\Users\wu\AppData\Roaming\nvm\v11.10.0\node_modules\truffle\build\webpack:\~\web3-eth\~\web3-core-requestmanager\src\index.js:140:1
    at C:\Users\wu\AppData\Roaming\nvm\v11.10.0\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:112:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\wu\AppData\Roaming\nvm\v11.10.0\node_modules\truffle\build\webpack:\~\web3\~\web3-providers-http\src\index.js:96:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\wu\AppData\Roaming\nvm\v11.10.0\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request-event-target.js:34:1)
    at XMLHttpRequest._setReadyState (C:\Users\wu\AppData\Roaming\nvm\v11.10.0\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request.js:208:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\wu\AppData\Roaming\nvm\v11.10.0\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request.js:318:1)
    at IncomingMessage.<anonymous> (C:\Users\wu\AppData\Roaming\nvm\v11.10.0\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request.js:289:47)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Truffle v5.0.5 (core: 5.0.5)
Node v11.10.0

```

**Comment by wuyuyue** [comment]
fixed by #27

**Comment by timmyz** [comment]
i got the same issue with the latest code.
```
truffle migrate
Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Error: Returned error: Method not found
    at Object.ErrorResponse (/Users/timmyzhang/.config/yarn/global/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-helpers/src/errors.js:29:1)
    at /Users/timmyzhang/.config/yarn/global/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-requestmanager/src/index.js:140:1
    at /Users/timmyzhang/.config/yarn/global/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at XMLHttpRequest.request.onreadystatechange (/Users/timmyzhang/.config/yarn/global/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/timmyzhang/.config/yarn/global/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest._setReadyState (/Users/timmyzhang/.config/yarn/global/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequest._onHttpResponseEnd (/Users/timmyzhang/.config/yarn/global/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at IncomingMessage.<anonymous> (/Users/timmyzhang/.config/yarn/global/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
    at IncomingMessage.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Truffle v5.0.17 (core: 5.0.16)
Node v11.7.0
```

**Comment by wuyuyue** [comment]
the last step, please run "yarn migrate" instead of "truffle migrate"
we rewrite truffle-migrate as cita-truffle-migrate
